# core system
base
base-devel
linux
linux-firmware

# boot / system setup
grub
efibootmgr
os-prober
reflector

# networking
networkmanager
openssh

# audio
alsa-utils
pipewire-alsa
pipewire-jack
pipewire-pulse
sof-firmware

# bluetooth
bluedevil
bluez
bluez-utils

# desktop environment (kde)
plasma-desktop
plasma-nm
plasma-pa
plasma-systemmonitor
dolphin
kinfocenter
kscreen
kwallet-pam
kwalletmanager
sddm
sddm-kcm

# terminal utils
gnome-terminal
neovim
tmux
vim
wl-clipboard

# dev tools
git
stow

# gaming
steam
