# core system
base
base-devel
linux
linux-firmware

# boot / system setup
efibootmgr
grub
os-prober
reflector

# networking
networkmanager
openssh

# audio
alsa-utils
pipewire-alsa
pipewire-jack
pipewire-pulse
sof-firmware

# bluetooth
bluedevil
bluez
bluez-utils

# desktop environment (kde)
dolphin
kinfocenter
kscreen
kwallet-pam
kwalletmanager
plasma-desktop
plasma-nm
plasma-pa
plasma-systemmonitor
sddm
sddm-kcm

# terminal utils
gnome-terminal
less
neovim
tmux
vim
wl-clipboard

# dev tools
git
man-db
man-pages
stow

# gaming
steam

