# core system
base
base-devel
linux
linux-firmware
linux-headers

# boot / system setup
btop
efibootmgr
grub
os-prober
reflector

# networking
bind
firewalld
networkmanager
networkmanager-openvpn
openssh
openvpn

# audio
alsa-utils
pipewire-alsa
pipewire-jack
pipewire-pulse
sof-firmware

# bluetooth
bluedevil
bluez
bluez-utils

# desktop environment (kde)
dolphin
kinfocenter
kscreen
kwallet-pam
kwalletmanager
plasma-desktop
plasma-nm
plasma-pa
plasma-systemmonitor
sddm
sddm-kcm

# terminal utils
ghostty
less
neovim
tmux
vim
wl-clipboard

# dev tools
apache
bear
docker
git
man-db
man-pages
obsidian
stow
unzip
zip

# gaming
lib32-vulkan-radeon
obs-studio
steam

