# unbind arrow keys
unbind Left
unbind Down
unbind Up
unbind Right
# vim style arrow keys
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# unbind resize
unbind C-Left
unbind C-Down
unbind C-Up
unbind C-Right
# vim style arrow keys
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# unbind bigger resize
unbind M-Left
unbind M-Down
unbind M-Up
unbind M-Right
# vim style arrow keys
bind -r M-h resize-pane -L 10
bind -r M-j resize-pane -D 10
bind -r M-k resize-pane -U 10
bind -r M-l resize-pane -R 10

# unbind split-window
unbind %
unbind '"'
# vim style split
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
# create new window with current path as well
bind c new-window -c "#{pane_current_path}"

bind & kill-window # still unsure of this one
# unbind kill-pane
unbind x
# vim style kill
bind-key q kill-pane
