# Default repeat time is too long!!!!!
set-option -g repeat-time 250

# use vim keybinds after a '[' for scrolling
set-window-option -g mode-keys vi
set -g status-keys vi

# unbind arrow keys
unbind Left
unbind Down
unbind Up
unbind Right
# vim style arrow keys
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# unbind resize
unbind C-Left
unbind C-Down
unbind C-Up
unbind C-Right
# vim style arrow keys
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# unbind bigger resize
unbind M-Left
unbind M-Down
unbind M-Up
unbind M-Right
# vim style arrow keys
bind -r M-h resize-pane -L 10
bind -r M-j resize-pane -D 10
bind -r M-k resize-pane -U 10
bind -r M-l resize-pane -R 10

# unbind split-window
unbind %
unbind '"'
# vim style split
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
# create new window with current path as well
bind c new-window -c "#{pane_current_path}"

bind & kill-window # still unsure of this one
# unbind kill-pane
unbind x
# vim style kill
bind-key q kill-pane

# tpm plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# restore last tmux session on open
set -g @continuum-restore 'on'

# uses vim-obsession's session to backup nvim
set -g @resurrect-strategy-nvim 'session'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
