alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -lA'
alias grep='rg --color=auto'
alias vi='vim'
alias nv='nvim'
alias gs='git status'
alias gl='git log'
alias gd='git diff'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias gr='git restore'
